dist: focal

language: cpp

os: linux
arch:
  - amd64
  - ppc64le

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7

sudo: false

before_script:
  - mkdir debug
  - cd debug
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCHARLS_PEDANTIC_WARNINGS=On -DCHARLS_TREAT_WARNING_AS_ERROR=On ..

script: make
